apiVersion: v1
kind: Pod
metadata:
  name: client-simulator
  labels:
    run: client-simulator
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: test-server
      resources:
        limits:
          cpu: 50m
          memory: 150Mi
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 1 && curl fe.istio-playground.svc.cluster.local; done"
