apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hs-server
  name: hs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hs-server
  strategy: {}
  template:
    metadata:
      labels:
        app: hs-server
    spec:
      containers:
        - image: node:18-alpine
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/node", "/etc/code/node-server.js"]
          name: test-server
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
          volumeMounts:
            - name: config-volume
              mountPath: /etc/code
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EXTERNAL_SERVERS
              value: "http://crm.istio-playground.svc.cluster.local http://payment-gateway.istio-playground.svc.cluster.local"
            - name: SLEEP_DURATION
              value: "0" # 10 seconds
      volumes:
        - name: config-volume
          configMap:
            name: node-server-code
---
apiVersion: v1
kind: Service
metadata:
  name: hs-server
spec:
  selector:
    app: hs-server
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
