apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: team-nginx
    run: server
  name: server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: team-nginx
    run: server
  type: NodePort
