apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: kong
  namespace: argocd
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress
    repoURL: https://charts.konghq.com
    targetRevision: 0.*.* # any version of first major release
    helm:
      releaseName: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - ServerSideApply=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
